language: android

script: "./gradlew build"

android:
  components:
    - build-tools 21.1.2
    - sys-img-armeabi-v7a-android-21
    - android-21
    - extra
    
branches:
  except:
    - gh-pages
    
notifications:
  email: false

sudo: false
